--local variables for API. Automatically generated by https://github.com/simpleavaster/gslua/blob/master/authors/sapphyrus/generate_api.lua 
local client_latency, client_log, client_draw_rectangle, client_draw_circle_outline, client_userid_to_entindex, client_draw_indicator, client_draw_gradient, client_set_event_callback, client_screen_size, client_eye_position = client.latency, client.log, client.draw_rectangle, client.draw_circle_outline, client.userid_to_entindex, client.draw_indicator, client.draw_gradient, client.set_event_callback, client.screen_size, client.eye_position 
local client_draw_circle, client_color_log, client_delay_call, client_draw_text, client_visible, client_exec, client_trace_line, client_set_cvar = client.draw_circle, client.color_log, client.delay_call, client.draw_text, client.visible, client.exec, client.trace_line, client.set_cvar 
local client_world_to_screen, client_draw_hitboxes, client_get_cvar, client_draw_line, client_camera_angles, client_draw_debug_text, client_random_int, client_random_float = client.world_to_screen, client.draw_hitboxes, client.get_cvar, client.draw_line, client.camera_angles, client.draw_debug_text, client.random_int, client.random_float 
local entity_get_local_player, entity_is_enemy, entity_hitbox_position, entity_get_player_name, entity_get_steam64, entity_get_bounding_box, entity_get_all, entity_set_prop = entity.get_local_player, entity.is_enemy, entity.hitbox_position, entity.get_player_name, entity.get_steam64, entity.get_bounding_box, entity.get_all, entity.set_prop 
local entity_is_alive, entity_get_player_weapon, entity_get_prop, entity_get_players, entity_get_classname = entity.is_alive, entity.get_player_weapon, entity.get_prop, entity.get_players, entity.get_classname 
local globals_realtime, globals_absoluteframetime, globals_tickcount, globals_curtime, globals_mapname, globals_tickinterval, globals_framecount, globals_frametime, globals_maxplayers = globals.realtime, globals.absoluteframetime, globals.tickcount, globals.curtime, globals.mapname, globals.tickinterval, globals.framecount, globals.frametime, globals.maxplayers 
local ui_new_slider, ui_new_combobox, ui_reference, ui_set_visible, ui_is_menu_open, ui_new_color_picker, ui_set_callback, ui_set, ui_new_checkbox, ui_new_hotkey, ui_new_button, ui_new_multiselect, ui_get = ui.new_slider, ui.new_combobox, ui.reference, ui.set_visible, ui.is_menu_open, ui.new_color_picker, ui.set_callback, ui.set, ui.new_checkbox, ui.new_hotkey, ui.new_button, ui.new_multiselect, ui.get 
local math_ceil, math_tan, math_log10, math_randomseed, math_cos, math_sinh, math_random, math_huge, math_pi, math_max, math_atan2, math_ldexp, math_floor, math_sqrt, math_deg, math_atan, math_fmod = math.ceil, math.tan, math.log10, math.randomseed, math.cos, math.sinh, math.random, math.huge, math.pi, math.max, math.atan2, math.ldexp, math.floor, math.sqrt, math.deg, math.atan, math.fmod 
local math_acos, math_pow, math_abs, math_min, math_sin, math_frexp, math_log, math_tanh, math_exp, math_modf, math_cosh, math_asin, math_rad = math.acos, math.pow, math.abs, math.min, math.sin, math.frexp, math.log, math.tanh, math.exp, math.modf, math.cosh, math.asin, math.rad 
local table_maxn, table_foreach, table_sort, table_remove, table_foreachi, table_move, table_getn, table_concat, table_insert = table.maxn, table.foreach, table.sort, table.remove, table.foreachi, table.move, table.getn, table.concat, table.insert 
local string_find, string_format, string_rep, string_gsub, string_len, string_gmatch, string_dump, string_match, string_reverse, string_byte, string_char, string_upper, string_lower, string_sub = string.find, string.format, string.rep, string.gsub, string.len, string.gmatch, string.dump, string.match, string.reverse, string.byte, string.char, string.upper, string.lower, string.sub 
--end of local variables 

--set this to true to enable custom skyboxes (community servers)
local enable_custom = false

local function set_skybox(skybox_name)
	client_set_cvar("sv_skyname", skybox_name)
end

local brightness_reference = ui.reference("VISUALS", "Effects", "Brightness adjustment")
local enabled_prev = false
local skyname_original

local skyboxes = {
	["Tibet"]="cs_tibet",
	["Baggage"]="cs_baggage_skybox_",
	["Monastery"]="embassy",
	["Italy/OldInferno"]="italy",
	["Aztec"]="jungle",
	["Vertigo"]="office",
	["Daylight"]="sky_cs15_daylight01_hdr",
	["Daylight (2)"]="vertigoblue_hdr",
	["Clouds"]="sky_cs15_daylight02_hdr",
	["Clouds (2)"]="vertigo",
	["Gray"]="sky_day02_05_hdr",
	["Clear"]="nukeblank",
	["Canals"]="sky_venice",
	["Cobblestone"]="sky_cs15_daylight03_hdr",
	["Assault"]="sky_cs15_daylight04_hdr",
	["Clouds (Dark)"]="sky_csgo_cloudy01",
	["Night"]="sky_csgo_night02",
	["Night (2)"]="sky_csgo_night02b",
	["Night (Flat)"]="sky_csgo_night_flat",
	["Dusty"]="sky_dust",
	["Rainy"]="vietnam",
	["Custom: Sunrise"]="amethyst",
	["Custom: Galaxy"]="sky_descent",
	["Custom: Galaxy (2)"]="clear_night_sky",
	["Custom: Galaxy (3)"]="otherworld",
	["Custom: Clouds (Night)"]="cloudynight",
	["Custom: Ocean"]="dreamyocean",
	["Custom: Grimm Night"]="grimmnight",
	["Custom: Heaven"]="sky051",
	["Custom: Heaven (2)"]="sky081",
	["Custom: Clouds"]="sky091",
	["Custom: Night (Blue)"]="sky561",
}
local function get_skybox_names()
	local skybox_names = {}
	for k,v in pairs(skyboxes) do
		if not (enable_custom == false and string_sub(k, 1, 8) == "Custom: ") then
		  table_insert(skybox_names, k)
		end
	end
	table_sort(skybox_names)
	table_insert(skybox_names, 1, "Off")
	return skybox_names
end

local skybox_reference = ui.new_combobox("VISUALS", "Effects", "Override skybox", get_skybox_names())

local function on_skybox_changed()
	local skybox = ui_get(skybox_reference)
	local skybox_name
	if skybox == "Off" then
		if enabled_prev then
			if skyname_original ~= nil then
				skybox_name = skyname_original
			else
				if ui_get(brightness_reference) then
					skybox_name = "sky_csgo_night02"
				else
					skybox_name = "sky_dust"
				end
			end
		end
	else
		skybox_name = skyboxes[skybox]
		if not enabled_prev then
			skyname_original = client_get_cvar("sv_skyname")
		end
	end
	set_skybox(skybox_name)
	enabled_prev = skybox ~= "Off"
end
ui.set_callback(skybox_reference, on_skybox_changed)

local function on_player_spawn(e)
	if client_userid_to_entindex(e.userid) == entity_get_local_player() then
		on_skybox_changed()
	end
end
client.set_event_callback("player_spawn", on_player_spawn)
